### ISSUE TITLE
Show line numbers

### ISSUE THREAD

**Issue by Ceda-EI** [MKRhere/bin#1]

**Comment by pavanjadhaw** [comment]
:clinking_glasses:  Feature added in https://github.com/MKRhere/bin/commit/dfbeb2c77519cea54537e8da700e025a13ca1995

**Comment by MKRhere** [comment]
Thanks for the comment @pavanjadhaw 😉 Closing 

_Sent from my ZenFone Max Pro (M1) using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_
